namespace MarketHub.Application.Contracts.Admin.Messaging.EmailMessageTemplate.Requests.GetById;

using Dto;

public sealed record EmailMessageTemplateGetByIdResponse(EmailMessageTemplateGetByIdDto EmailMessageTemplate);